import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Layout from '../components/Layout';

export default function Home() {
  return (
    <Layout pageTitle="Home Page">
      <div className="testing">Contoh content</div>
      <Image src="/profile.jpg" width={200} height={200} alt="profile" />
      <h1 className={styles['title-homepage']}>Wellcome Belly Brata</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <Image src="/profile.jpg" width={200} height={200} alt="profile" />
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <Image src="/profile.jpg" width={200} height={200} alt="profile" />
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <Image src="/profile.jpg" width={200} height={200} alt="profile" />
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <Image src="/profile.jpg" width={200} height={200} alt="profile" />
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <Image src="https://cdn.app.jcodelivery.com/img/menu/promo-20210802-dnt.jpg" width={200} height={200} alt="profile" />
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <Image src="/post2.jpg" width={200} height={200} alt="image-post-2" />
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <Image src="/post1.jpg" className={styles.imageTest} width={200} height={200} alt="image-post-1" />
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus euismod ante tempus egestas. Nunc maximus efficitur ullamcorper. Vestibulum congue accumsan libero. Maecenas porttitor lacinia velit, et condimentum sem. Fusce at nibh sed enim fermentum rutrum. Duis eu leo nec lorem pellentesque interdum. Aliquam metus nulla, imperdiet non convallis sed, pellentesque in enim. Quisque commodo a erat at porta. Maecenas et ipsum congue, mollis neque at, ultricies lectus. Quisque semper tristique mattis. Sed dolor diam, fermentum sit amet turpis vel, ullamcorper maximus lorem. Vestibulum tincidunt lorem sed sem malesuada, consequat venenatis justo tincidunt. Morbi malesuada faucibus metus a laoreet. Aliquam commodo pretium eros, vitae aliquam nisi.</p>
    </Layout>
  );
}
